### ISSUE TITLE
BLS12-381 fails in a powersoftau contribute command. Curve not supported.

### ISSUE THREAD

**Issue by glamperd** [iden3/ffjavascript#36]
snarkJS: Error: Curve not supported: 4002409555221667610661788685990436838824310417315709160196267947217350388461752218928110433526561144555515641069568
    at getCurveFromQ (/home/root/snarkjs/build/cli.cjs:765:15)
    at readPTauHeader (/home/root/snarkjs/build/cli.cjs:842:25)
    at async contribute (/home/root/snarkjs/build/cli.cjs:2408:43)
    at async Object.powersOfTauContribute [as action] (/home/root/snarkjs/build/cli.cjs:8619:12)
    at async clProcessor (/home/root/snarkjs/build/cli.cjs:304:27)

**Comment by glamperd** [comment]
When logged in base 16, the q values retrieved from the file is this: `Curve not supported>>>: 1a0111ea397fe70000000000000000000000000000000000000000000000000000000000000000000000000000000000` It lost precision from the original value.

**Comment by phated** [comment]
Fixed by #37 but we need to update ffjavascript to  in all of the dependent repos
